CREATE TABLE "ROOT"."EMPLOYEE" 
   (	"EMP_ID" NUMBER(8) NOT NULL PRIMARY KEY, 
	"EMPLOYEE_FNAME" VARCHAR2(100) NOT NULL, 
	"EMPLOYEE_LNAME" VARCHAR2(100) NOT NULL, 
	"DEPT_ID" NUMBER(10) NOT NULL
   );
   
   
   
DROP TABLE ROOT.EMPLOYEE;
COMMIT;
SELECT * FROM ROOT.EMPLOYEE;


SET AUTOCOMMIT;


SELECT EMPLOYEE_FNAME, EMPLOYEE_LNAME FROM ROOT.EMPLOYEE WHERE DEPT_ID = '1';
ALTER TABLE ROOT.EMPLOYEE ADD AGE NUMBER(3); 


UPDATE ROOT.EMPLOYEE SET AGE = 25 WHERE EMP_ID = '12345678';
UPDATE ROOT.EMPLOYEE SET AGE = 60 WHERE EMP_ID = '13242';
UPDATE ROOT.EMPLOYEE SET AGE = 51 WHERE EMP_ID = '342395';
UPDATE ROOT.EMPLOYEE SET AGE = 39 WHERE EMP_ID = '449927';
UPDATE ROOT.EMPLOYEE SET AGE = 43 WHERE EMP_ID = '399287';


SELECT EMPLOYEE_FNAME, EMPLOYEE_LNAME FROM ROOT.EMPLOYEE WHERE AGE > '30';


CREATE TABLE "ROOT"."DEPARTMENT" 
   (	"DEPT_ID" NUMBER(10) NOT NULL, 
	"DEPT_NAME" VARCHAR2(20) NOT NULL
   );
   
CREATE TABLE ROOT.LOOKUP
    (   "EMP_ID" NUMBER(8) NOT NULL , 
        "DEPT_ID" NUMBER(10) NOT NULL,
        "LOOKUP_ID" NUMBER(8) NOT NULL PRIMARY KEY
    );


ALTER TABLE ROOT.LOOKUP ADD CONSTRAINT FK_EMP_ID FOREIGN KEY(EMP_ID) REFERENCES ROOT.EMPLOYEE(EMP_ID);
ALTER TABLE ROOT.LOOKUP ADD CONSTRAINT FK_DEPT_ID FOREIGN KEY(DEPT_ID) REFERENCES ROOT.DEPARTMENT(DEPT_ID);